### PR TITLE
Add a reset() method to CancelToken

### PR DESCRIPTION
**Pull request by gsalgado**
Needed for https://github.com/ethereum/py-evm/pull/1189

### CODE REVIEW

**Review by pipermerriam — CHANGES_REQUESTED** [review]
What about chained tokens?  It seems like this would have undefined or un-intuitive behavior when a token is considered triggered because of an upstream chained token at which point IIUC this would do nothing and the token would remain triggered.

**Comment by gsalgado** [comment]
The only use case we have for this right now is so that we can restart a `BaseService` that had its token triggered as part of the cleanup executed when `_run()` returns. Would you be ok with having `reset()`'s docstring make it clear it can only be used on a token which has been triggered itself (i.e. has `self._triggered` set) and doesn't have any chained tokens that are also triggered? It would also raise an error in any of those conditions

**Comment by pipermerriam** [comment]
Yes, changing `reset` to throw an error if the token has been triggered by an upstream chained token would be an acceptable solution to this for me.

- if triggered upstream -> exception
- if triggered locally -> resets
- if not triggered -> noop

(Though I think my other comment about not restarting child services in the related py-evm PR may make this PR un-needed if we go that route)

**Comment by carver** [comment]
It's much easier to reason about a service that has a single life-cycle. I'm highly in favor of alternative options, like generating a new instance.

**Pull request closed without merging**
